name: med_assist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter:
  device_preview: ^1.1.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  country_phone_code_picker: ^0.0.41
  pinput: ^2.2.12
  google_maps_flutter: ^2.2.0
  share: ^2.0.4
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  toggle_switch: ^2.0.1
  flutter_slidable: ^2.0.0
  percent_indicator: ^4.2.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutter_progress_hud: ^2.0.2
  cloud_firestore: ^4.0.5
  geocoding: ^2.0.5
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  firebase_storage: ^11.0.5
  url_launcher: ^6.1.6
  geolocator: ^9.0.2
  rename: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_rating_stars: ^1.0.3+4
  email_validator: ^2.1.17
flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconlauncher.png"
  jiffy: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^2.3.9
  flutter_polyline_points: ^1.0.0
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
 





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dialog_flow_auth.json
    - assets/images/logo/
    - assets/images/homeScreen/
    - assets/googleMapStyles/
    - assets/images/selectionScreen/
    - assets/images/homeScreen/Drawer/
    - assets/images/extra/safetyScreen/
    - assets/images/extra/
  #   - images/a_dot_ham.jpeg


 

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
